// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package data

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/bg.png
var bg []byte

//go:embed assets/logo-white.png
var logoWhite []byte

//go:embed assets/logo-black.png
var logoBlack []byte

//go:embed assets/font/out.ttf
var font []byte

var Bg = &fyne.StaticResource{
	StaticName:    "bg.png",
	StaticContent: bg,
}
var LogoWhite = &fyne.StaticResource{
	StaticName:    "logo-white.png",
	StaticContent: logoWhite,
}
var LogoBlack = &fyne.StaticResource{
	StaticName:    "logo-black.png",
	StaticContent: logoBlack,
}
var FontSmileySansOblique = &fyne.StaticResource{
	StaticName:    "SmileySans-Oblique.ttf",
	StaticContent: font,
}
