name: release

on:
  push:
    tags:
      - 'vv*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Set up Cross-compile ENV
        run: |
          sudo apt update
          sudo apt install gcc libc6-dev libgl1-mesa-dev
          sudo apt install libx11-dev xorg-dev libxtst-dev libpng++-dev
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo apt install libxkbcommon-dev
          sudo apt install xsel xclip
          sudo apt-get install gcc-multilib
          sudo apt-get install gcc-mingw-w64
          sudo apt install libz-mingw-w64-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
